name: Docker Image CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
concurrency:
  group: ci-workflow
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |-
            shelgir/kubak-landing-api:latest
            shelgir/kubak-landing-api:${{ github.sha }}
            shelgir/kubak-landing-api:${{ github.ref_name }}
